Author.create!([
  {name: " Chris Kuzneski", birthday: "1969-09-02", description: "Chris Kuzneski (born 1969) is a New York Times bestselling American author.[1] His books have been translated into more than 20 languages, have been published in more than 40 countries, and have sold millions of copies.[2] His latest book, The Prisoner's Gold, was just named a finalist for E-Book of the Year by International Thriller Writers (ITW).[3] His works have also been honored by the Florida Book Awards and named a Literary Guild's featured selection.[4] In 2015, the Malta Tourism Authority invited Kuzneski to Malta in order to thank him for mentioning their country in his books.[5]", homeland: "American"},
  {name: "Pradeep Kumar Sinha", birthday: "1955-07-18", description: "Pradeep Kumar Sinha (P. K. Sinha) (born July 18, 1955) is an Indian civil servant who is the 31st Cabinet Secretary of the Republic of India.[1][2] He is an Uttar Pradesh cadre IAS officer of 1977 batch. He is the Ex Power secretary of India and before that he served as Secretary in Ministry of Shipping and is an Economics graduate from St. Stephens College, Delhi University and holds a Masters Degree in Economics from the Delhi School of Economics. He holds a Mphil degree as well . [3]", homeland: "Indian"},
  {name: "Kazue Katō (加藤和恵, Katō Kazue)", birthday: "1980-07-20", description: "Kazue Katō (加藤和恵, Katō Kazue), born on July 20th, 1980 in the district of Shinjuku, in Tokyo, is a Japanese mangaka, specifically an author of shōnen manga. She is mainly known to be the author of Blue Exorcist. She also created Robot to Usakichi ( ロボとうさ吉 ), for which she received the Osamu Tezuka Award.", homeland: "Tokyo"},
  {name: "Nir Eyal", birthday: "1980-02-19", description: "Nir Eyal is an Israeli-American author, educator, and entrepreneur.[2] In addition to his personal blog, NirAndFar.com, he is a frequent contributing writer for Forbes, TechCrunch,[3] and Psychology Today – writing about the intersection of psychology, technology, and business. Nir frequently writes about how technology shapes user behavior by creating new habits.", homeland: "American"},
  {name: "Jack Thorne", birthday: "1978-12-06", description: "Jack Thorne was born on December 6, 1978, in Bristol. He is a BAFTA Award-winning screenwriter and playwright. He has written for radio, theatre and film, most notably on the TV shows Skins, Cast-offs, This Is England '86, This Is England '88, The Fades and the feature film The Scouting Book for Boys. He currently lives in Luton.", homeland: "Bristol"},
  {name: "J. K. Rowling", birthday: "1965-07-31", description: "Joanne \"Jo\" Rowling, OBE, FRSL (/ˈroʊlɪŋ/; born 31 July 1965), pen names J. K. Rowling and Robert Galbraith, is a British novelist, screenwriter and film producer best known as the author of the Harry Potter fantasy series. The books have gained worldwide attention, won multiple awards, and sold more than 400 million copies.[1] They have become the best-selling book series in history[2] and been the basis for a series of films which is the second highest-grossing film series in history.[3] Rowling had overall approval on the scripts[4] and maintained creative control by serving as a producer on the final instalment.[5]", homeland: "British"},
  {name: " Dan Brown", birthday: "1964-07-22", description: "Daniel \"Dan\" Brown (born June 22, 1964) is an American author of thriller fiction who is best known for the 2003 bestselling novel The Da Vinci Code.[1] Brown's novels are treasure hunts set in a 24-hour period,[2] and feature the recurring themes of cryptography, keys, symbols, codes, and conspiracy theories. His books have been translated into 52 languages, and as of 2012, sold over 200 million copies. Three of them, Angels & Demons (2000), The Da Vinci Code (2003), and Inferno (2013), have been or are being adapted into films.", homeland: "American"},
  {name: "Alan Furst", birthday: "1941-06-20", description: "Alan Furst (born February 20, 1941) is an American author of historical spy novels. Furst has been called \"an heir to the tradition of Eric Ambler and Graham Greene,\" whom he cites along with Joseph Roth and Arthur Koestler as important influences. Most of his novels since 1988 have been set just prior to or during the Second World War and he is noted for his successful evocations of Eastern European peoples and places during the period from 1933 to 1944.", homeland: "American"},
  {name: "Santosh Kumar", birthday: "1982-07-11", description: "Syed Musa Raza, (December 25, 1925 – June 11, 1982) better known as Santosh Kumar (Punjabi, Urdu: سنتوش کمار‎), was a famous Pakistani film actor of 1950s and 1960s era. He belonged to a well educated Urdu speaking family from Uttar Pradesh, India. He was married to Sabiha Khanum. His brother Darpan was also a renowned film actor during that period. His other brother S. Suleiman was a renowned film director.", homeland: "Pakistani"},
  {name: "Nick Bostrom", birthday: "1973-03-10", description: "Nick Bostrom (English /ˈbɒstrəm/; Swedish: Niklas Boström, IPA: [ˈbuːˈstrœm]; born 10 March 1973)[1] is a Swedish philosopher at the University of Oxford known for his work on existential risk, the anthropic principle, human enhancement ethics, superintelligence risks, the reversal test, and consequentialism. He holds a PhD from the London School of Economics (2000). In 2011, he founded the Oxford Martin Programme on the Impacts of Future Technology,[2] and he is currently the founding director of the Future of Humanity Institute[3] at Oxford University.", homeland: "Helsingborg, Sweden"},
  {name: "Martin Odersky", birthday: "1958-09-05", description: "Martin Odersky (born 5 September 1958) is a German[1] computer scientist and professor of programming methods at EPFL in Switzerland. He specializes in code analysis and programming languages. He designed the Scala programming language[2][3] and Generic Java (and Pizza before[4]) both with others, and built the current generation of javac, the Java compiler. In 2007, he was inducted as a Fellow of the Association for Computing Machinery.", homeland: "Lausanne, Switzerland"}
])
Book.create!([
  {name: "The Prisoner's Gold (The Hunters 3)", description: "The Hunters return in their third brilliant novel from the Sunday Times Top Ten bestselling author Chris Kuzneski, whose writing James Patterson says has 'raw power'. The team are hunting Marco Polo's hidden treasure, but who is on their tail? The Hunters if you seek, they will find...The travels of Marco Polo are known throughout the world. But what if his story isn't complete? What if his greatest adventure has yet to be discovered? Guided by a journal believed to have been dictated by Polo himself, the Hunters set out in search of his final legacy: the mythical treasure gathered during Polo's lifetime of exploration. But as every ancient clue brings them closer to the truth, each new step puts them in increasing danger....Explosive action. Killer characters. Classic Kuzneski.", price: "259.0", image_url: nil, image: File.open("#{Rails.root}/public/uploads/The_Prisoner_s_Gold.jpg"), staff_id: 1, author_id: 1, manufacturer_id: 1},
  {name: "Harry Potter and the Cursed Child - Parts I & II (Special Rehearsal Edition)", description: "The Eighth Tale in the Harry Potter Saga\r\nBeing labelled as 'the boy who lived' for his whole life has not been easy for Harry Potter. In the official eighth instalment of the Harry Potter series penned in the form of a two-part stage production play, J. K. Rowling weaves yet another thrilling and magical yarn featuring the life of Harry Potter nineteen years later in the post-Voldemort wizarding world.\r\n\r\nA glimpse into the epic tale\r\nHarry Potter plays the role of a man finally living out the quiet, conventional lifestyle he always wanted to live as a Minister of Magic employee, who is a doting husband and father of three. Yet, he struggles to escape the haunting past, the demons of which continue to consume him. The play also features a grown up Albus Severus Potter following the footsteps of his legendary father and labouring to carry the burden of a family bequest and fortune he hadn't expected. As the past meets the present, the legendary father and son duo strive to come in terms with the darkness that lies within and overcome their inner demons.\r\n\r\nThe Play\r\nThe 'Harry Potter And The Cursed Child: The Play' airs for the first time at the London Palace Theatre on July 30th, 2016. The play is based on the book written by Jack Thorne in collaboration with J. K. Rowling and the book is scheduled to release on July 31st, 2016. On 10th February, 2016, it was declared that the scripts of both the parts of the play would be released in both digital and print formats.\r\n\r\nJ. K. Rowling promises to take fans deeper into the recesses of Harry Potter's mind as the play showcases the life of Potter when he was an unwanted orphan.\r\n\r\nAbout The Author\r\nHarry Potter has often been declared as one of the most read and most loved sagas by children and adults alike; each book explores the wondrous world of wizards and leaves us with relatable lessons that has kept even adults glued to these books for years and years. Born in England, Joanne \"Jo\" Rowling conceived the entire plot for the Harry Potter series on a train-ride as she was working as a researcher for Amnesty International. The first novel in the seven-part series, Harry Potter and The Philosopher's Stone was launched in 2000. And the rest as we know it, is history!\r\n\r\nYou can bag this book from Amazon.in today by following a few easy steps.", price: "601.0", image_url: nil, image: File.open("#{Rails.root}/public/uploads/Harry_Potter_and_the_Cursed_Child.jpg"), staff_id: 1, author_id: 6, manufacturer_id: 1},
  {name: "Angels and Demons (Robert Langdon)", description: "Angels and Demons was published on 28th August, 2010. It was the second bestseller written by the author, after The Da Vinci Code. The Da Vinci Code was more of treasure hunts and about things that fascinated Brown in his childhood. Angels and Demons is more about the unraveled truths and fights between religion and science and how it escalates into one big controversy. The secret brotherhood of the illuminati has always been a rival of the Catholic Church and now they are doing everything in their capability to destroy the Catholic Church. Robert Langdon is a world renowned symbologist from Harvard and is called upon the orders of the Swiss research facility to examine an anonymous symbol. This symbol was found carved on the chest of a physicist who was murdered. With all the clues gathered, he discovers that it could have been the work of the illuminati. They are the most influential underground organization ever to have walked the earth. On the eve of the Vatican's gathering, a messenger of the illuminati declares that they are going to blow up Vatican City as they have planted a bomb at the center of the city. With very less time in hand, Langdon rushes to Rome to try and stop the destruction. He and his partner Vittoria, an Italian scientist, set out to search through the deserted cathedrals, sealed crypts, catacombs and also the most secretive vault on planet earth. There are so many symbols involved that lead to the illuminati nest which was forgotten. Their quest to try and save the Vatican City is the most exciting crime story you can look for. This book is available in paperback.", price: "319.0", image_url: nil, image: File.open("#{Rails.root}/public/uploads/Angels_and_Demons__Robert_Langdon_.jpg"), staff_id: 1, author_id: 7, manufacturer_id: 1},
  {name: "Inferno (Robert Langdon)", description: "'Seek and ye shall find.'\r\n\r\nWith these words echoing in his head, eminent Harvard symbologist Robert Langdon awakes in a hospital bed with no recollection of where he is or how he got there. Nor can he explain the origin of the macabre object that is found hidden in his belongings. A threat to his life will propel him and a young doctor, Sienna Brooks, into a breakneck chase across the city of Florence. Only Langdon's knowledge of hidden passageways and ancient secrets that lie behind its historic facade can save them from the clutches of their unknown pursuers. With only a few lines from Dante's dark and epic masterpiece, The Inferno, to guide them, they must decipher a sequence of codes buried deep within some of the most celebrated artefacts of the Renaissance - sculptures, paintings, buildings - to find the answers to a puzzle which may, or may not, help them save the world from a terrifying threat. Set against an extraordinary landscape inspired by one of history's most ominous literary classics, Inferno is Dan Brown's most compelling and thought-provoking novel yet, a breathless race-against-time thriller that will grab you from page one and not let you go until you close the book.", price: "130.0", image_url: nil, image: File.open("#{Rails.root}/public/uploads/Inferno__Robert_Langdon_.jpg"), staff_id: 1, author_id: 7, manufacturer_id: 3},
  {name: "A Hero in France", description: "Spring, 1941. Britain is losing the war.\r\n\r\nParis is occupied by the Nazis, dark and silent at night. But when the clouds part, and moonlight floods the city, a Resistance leader called Mathieu steps out to begin his work. \r\nThe fighters of the French Resistance are determined not to give up. These courageous men and women - young and old, aristocrats and nightclub owners, teachers and students - help downed British airmen reach the border with Spain. In farmhouses and rural churches, in secret hotels, and on the streets, they risk everything to open Europe's sealed doors and lead Allied fighters to freedom.\r\n\r\nBut as the military police heightens surveillance, Mathieu and his team face a new threat, dispatched from the Reich to destroy them all.", price: "799.0", image_url: nil, image: File.open("#{Rails.root}/public/uploads/A_Hero_in_France.jpg"), staff_id: 1, author_id: 8, manufacturer_id: 4},
  {name: "Computer Fundamentals", description: "P K Sinha designed Computer Fundamentals to introduce its readers to important concepts in Computer Science. Computer Fundamentals is written in a manner that it can be used as a textbook for many introductory courses related to IT and Computer Science. For beginners, it is useful because of its sheer simplicity and explanation of fundamentals.\r\n\r\nThe book has numerous illustrative diagrams, practical examples, chapter summaries, end-of-chapter questions, and a glossary of important terms. Beginners in computer science can refer to this book for guidance as it provides a clear idea about the working of the machine. The book can also be used as a self-study material due to its easy language and well-refined content.\r\n\r\nThe book has covered some major topics like Number systems, Computer Codes, Binary arithmetic, Boolean Algebra, and Logic Circuits. Introductions to new concepts in computing, new topics, and classifications have been added. Illustrative diagrams and lecture notes have been updated and included.\r\n\r\nComputer Fundamentals was published by BPB Publications in 2004 and is available in paperback.", price: "145.0", image_url: nil, image: File.open("#{Rails.root}/public/uploads/Computer_Fundamentals.jpg"), staff_id: 1, author_id: 2, manufacturer_id: 5},
  {name: "JDBC 4.2, Servlet 3.1, and JSP 2.3 Includes JSF 2.2 and Design Patterns, Black Book ", description: "JDBC 4.2, Servlet 3.1 and JSP 2.3 Black Book is a unique book for self-learning – leading to the development of expertise in Java database and Web technologies, such as JDBC, Servlet, JSP, JSTL and JSF. The book is also useful for the readers who already know these concepts but want to gain an in-depth knowledge about them. The detailed explanation of each concept with interdependent examples and various situations to apply the concepts makes this book worthwhile.", price: "509.0", image_url: nil, image: File.open("#{Rails.root}/public/uploads/JDBC_4.2__Servlet_3.1__and_JSP_2.3_Includes_JSF_2.2_and_Design_Patterns__Black_Book.jpg"), staff_id: 1, author_id: 9, manufacturer_id: 2},
  {name: "Superintelligence: Paths, Dangers, Strategies", description: "The human brain has some capabilities that the brains of other animals lack. It is to these distinctive capabilities that our species owes its dominant position. Other animals have stronger muscles or sharper claws, but we have cleverer brains. \r\n\r\nIf machine brains one day come to surpass human brains in general intelligence, then this new superintelligence could become very powerful. As the fate of the gorillas now depends more on us humans than on the gorillas themselves, so the fate of our species then would come to depend on the actions of the machine superintelligence. \r\n\r\nBut we have one advantage: we get to make the first move. Will it be possible to construct a seed AI or otherwise to engineer initial conditions so as to make an intelligence explosion survivable? How could one achieve a controlled detonation? \r\n\r\nTo get closer to an answer to this question, we must make our way through a fascinating landscape of topics and considerations. Read the book and learn about oracles, genies, singletons; about boxing methods, tripwires, and mind crime; about humanity's cosmic endowment and differential technological development; indirect normativity, instrumental convergence, whole brain emulation and technology couplings; Malthusian economics and dystopian evolution; artificial intelligence, and biological cognitive enhancement, and collective intelligence. \r\n\r\nThis profoundly ambitious and original book picks its way carefully through a vast tract of forbiddingly difficult intellectual terrain. Yet the writing is so lucid that it somehow makes it all seem easy. After an utterly engrossing journey that takes us to the frontiers of thinking about the human condition and the future of intelligent life, we find in Nick Bostrom's work nothing less than a reconceptualization of the essential task of our time.", price: "1.0", image_url: nil, image: File.open("#{Rails.root}/public/uploads/Superintelligence_-_Paths__Dangers__Strategies.jpg"), staff_id: 1, author_id: 10, manufacturer_id: 2},
  {name: "Programming in Scala", description: "In this practical book, four Cloudera data scientists present a set of self-contained patterns for performing large-scale data analysis with Spark. The authors bring Spark, statistical methodsand real-world data sets together to teach you how to approach analytics problems by example\r\n\r\nYou’ll start with an introduction to Spark and its ecosystem and then dive into patterns that apply common techniques classification, collaborative filtering and anomaly detection among others - to fields such as genomics, security and finance. If you have an entry-level understanding of machine learning and statistics and you program in Java, Python or Scala, you’ll find these patterns useful for working on your own data applications.", price: "2644.0", image_url: nil, image: File.open("#{Rails.root}/public/uploads/Programming_in_Scala.jpg"), staff_id: 1, author_id: 10, manufacturer_id: 4},
  {name: ".NET: Interview Questions", description: "Features: \r\n- This Book has been around 10 years in the industry and is the number one chosen friend when a C# developer is looking for a job. So do not look any further. Just pick it up. \r\n- This Book covers more than 1000 real time .NET interview questions ranging across 20 categories like .NET fundamentals, OOP, SQL Server, ADO.NET, MVC6, Angular, JQuery, HTML 5, WPF, WCF and so on... \r\n- The best part of this book is the DVD which has awesome step by step videos to learn MVC and .NET s soon as possible. \r\n- MVC and Angular are most trending topics. This book has 200 dedicated questions only for these two sections. \r\n- Lot of projects are still in maintenance phase So these are still requirements for WPF and WCF Skills as well. A dedicated topic with 100 Questions are given to these categories. \r\n- Lots of interviewers give importance to data access layer technologies like ADO.NET, EF and LINQ. 150 Questions are dedicated to these categories to ensure that you do not have issues in the interview. \r\n- If you are looking for senior position then interviewer probes around project management, UML, Design pattern and architecture questions. So we have separate chapters dedicated only for these topics. \r\n- We have also provided an excel assessment sheet by which you can assess how much you are redly for .NET Interviews. \r\n- When it comes to .NET interview SQL Server is the official RDBMS. So a separate chapter only dedicated to SQL Server so that you can handle questions around SQL Server. \r\n- Lot of interviewer’s ask questions on unusual topics like XML, threading, Remoting. Web Services. COM interop, Algorithm writing and so. We have special topics only dedicated to these sections so that you are prepared for any surprised questions. \r\n- With technical you should also know to create a good resume. A sample resume has been provided. \r\n- This book also discusses about current salary trend for .NET and C# developers so that when you go for an interview you should know what current market rate is ? and you negotiate it fairly.", price: "315.0", image_url: nil, image: File.open("#{Rails.root}/public/uploads/.NET-_Interview_Questions.jpg"), staff_id: 1, author_id: 7, manufacturer_id: 2},
  {name: "Blue Exorcist, Vol. 1", description: "Fight hellfire with hellfire!\r\n\r\nReads R to L (Japanese Style) for audiences T+.\r\n\r\nRaised by Father Fujimoto, a famous exorcist, Rin Okumura never knew his real father. One day a fateful argument with Father Fujimoto forces Rin to face a terrible truth – the blood of the demon lord Satan runs in Rin’s veins! Rin swears to defeat Satan, but doing that means entering the mysterious True Cross Academy and becoming an exorcist himself. Can Rin fight demons and keep his infernal bloodline a secret? It won't be easy, especially when drawing his father’s sword releases the demonic power within him!", price: "466.0", image_url: nil, image: File.open("#{Rails.root}/public/uploads/Blue_Exorcist__Vol._1.jpg"), staff_id: 1, author_id: 3, manufacturer_id: 6},
  {name: "Blue Exorcist, Vol. 2", description: "Reads R to L (Japanese Style) for audiences T+.\r\n\r\nRaised by Father Fujimoto, a famous exorcist, Rin Okumura never knew his real father. One day a fateful argument with Father Fujimoto forces Rin to face a terrible truth – the blood of the demon lord Satan runs in Rin’s veins! Rin swears to defeat Satan, but doing that means entering the mysterious True Cross Academy and becoming an exorcist himself. Can Rin fight demons and keep his infernal bloodline a secret? It won't be easy, especially when drawing his father’s sword releases the demonic power within him!", price: "450.0", image_url: nil, image: File.open("#{Rails.root}/public/uploads/Blue_Exorcist__Vol._2.jpg"), staff_id: 1, author_id: 3, manufacturer_id: 6},
  {name: "Blue Exorcist, Vol. 3", description: "Fight Hellfire with Hellfire!\r\n\r\nReads R to L (Japanese Style). \r\n\r\nRaised by Father Fujimoto, a famous exorcist, Rin Okumura never knew his real father. One day a fateful argument with Father Fujimoto forces Rin to face a terrible truth—the blood of the demon lord Satan runs in Rin’s veins! Rin swears to defeat Satan, but doing that means entering the mysterious True Cross Academy and becoming an exorcist himself. Can Rin fight demons and keep his infernal bloodline a secret? It won't be easy, especially when drawing his father’s sword releases the demonic power within him!\r\n\r\nAs a new Exorcist Esquire at True Cross Academy, Rin Okumura has a long way to go before he reaches the top rank of Paladin. When Rin and his classmates are sent to search for a ghost, Amaimon, King of Earth, takes Rin by surprise and steals the Koma Sword. Higher powers have been observing events at the academy and make their presence known. New players enter the game, and Rin doesn’t even know he’s playing!", price: "498.0", image_url: nil, image: File.open("#{Rails.root}/public/uploads/Blue_Exorcist__Vol._3.jpg"), staff_id: 1, author_id: 3, manufacturer_id: 6},
  {name: "Blue Exorcist, Vol. 4", description: "Fight Hellfire with Hellfire!\r\n\r\nReads R to L (Japanese Style). \r\n\r\nRaised by Father Fujimoto, a famous exorcist, Rin Okumura never knew his real father. One day a fateful argument with Father Fujimoto forces Rin to face a terrible truth—the blood of the demon lord Satan runs in Rin’s veins! Rin swears to defeat Satan, but doing that means entering the mysterious True Cross Academy and becoming an exorcist himself. Can Rin fight demons and keep his infernal bloodline a secret? It won't be easy, especially when drawing his father’s sword releases the demonic power within him!\r\n\r\nWhile most of the students at True Cross Academy head home for the summer break, Rin and his classmates are sent to a training camp in the forest district, and the right to go on a real mission is riding on their performance! Locating and recovering their objectives in the woods is tough and will require teamwork, skill and more than a little magic—and Rin will have to learn to rely on his friends. But is Mephisto masterminding something behind the scenes?!", price: "374.0", image_url: nil, image: File.open("#{Rails.root}/public/uploads/Blue_Exorcist__Vol._4.jpg"), staff_id: 1, author_id: 3, manufacturer_id: 6},
  {name: "Blue Exorcist, Vol. 5", description: "Fight Hellfire with Hellfire!\r\n\r\nReads R to L (Japanese Style). \r\n\r\nRaised by Father Fujimoto, a famous exorcist, Rin Okumura never knew his real father. One day a fateful argument with Father Fujimoto forces Rin to face a terrible truth—the blood of the demon lord Satan runs in Rin’s veins! Rin swears to defeat Satan, but doing that means entering the mysterious True Cross Academy and becoming an exorcist himself. Can Rin fight demons and keep his infernal bloodline a secret? It won't be easy, especially when drawing his father’s sword releases the demonic power within him!\r\n\r\nIn the late Edo Period, a demon known as the Impure King killed thousands of people. After defeating the demon, the Knights of the True Cross kept its left eye safely sealed away on Academy grounds—but now someone has stolen it! Hearing the thief has taken a child hostage, Yukio and Rin go to help. The investigation and pursuit will lead Rin and his friends to Kyoto and involve them even deeper in a sinister plot! But will his friends’ knowledge that Rin is the son of Satan drive a wedge between them?", price: "330.0", image_url: nil, image: File.open("#{Rails.root}/public/uploads/Blue_Exorcist__Vol._5.jpg"), staff_id: 1, author_id: 3, manufacturer_id: 6},
  {name: "Famous Flowers And Butterflies: Beautiful Blossoms and Flowers for Kids", description: "It is important to teach our children about the world that surrounds them. Sometimes, it can be difficult to find a method of learning children will enjoy. But if you combine the right elements, you can offer your child an exciting way to learn something new. If it is important to you to teach your children about the natural world, then using a famous flowers and butterflies picture book can be exceptionally useful. This picture book will be exciting to children because of the many colorful visions it offers of butterflies and flowers, and they can learn to identify many of them when using the book.", price: "69.0", image_url: nil, image: File.open("#{Rails.root}/public/uploads/Famous_Flowers_And_Butterflies-_Beautiful_Blossoms_and_Flowers_for_Kids.jpg"), staff_id: 1, author_id: 8, manufacturer_id: 1},
  {name: "Hooked: How to Build Habit-Forming Products", description: "The book, 'Hooked: How to Build Habit-Forming Products’ is an effective book for people who want to learn the art of selling products. This book derives strategies from stories of products that have made it big in their respective industries whilst citing the reasons for their success. Filled with critical insights, the usage of examples and anecdotes makes the content engaging and refreshing. The book is authored by Nir Eyal and was published by Portfolio Penguin publication in 2014. This book has received positive responses across the world and was in the list of Wall Street Journal business 'best selling' books. Plus, it won the award of 'best marketing book of the year' given by 1800CEOREAD.\r\n\r\nThe market is full of products that have similar qualities. However, very few of these products grow successful over the years.", price: "408.0", image_url: nil, image: File.open("#{Rails.root}/public/uploads/Hooked_-_How_to_Build_Habit-Forming_Products.jpg"), staff_id: 1, author_id: 9, manufacturer_id: 3},
  {name: "The Kite Runner", description: "Afghanistan, 1975: Twelve-year-old Amir is desperate to win the local \r\nkite-fighting tournament and his loyal friend Hassan promises to help \r\nhim. But neither of the boys can foresee what will happen to Hassan that\r\nafternoon, an event that is to shatter their lives. After the Russians \r\ninvade and the family is forced to flee to America, Amir realises that \r\none day he must return to Afghanistan under Taliban rule to find the one\r\nthing that his new world cannot grant him: redemption.", price: "137.75", image_url: nil, image: File.open("#{Rails.root}/public/uploads/The_Kite_Runner.jpg"), staff_id: 1, author_id: 8, manufacturer_id: 1},
  {name: "Start Calligraphy: The Right Way to Write", description: "Let calligraphy one of the easiest ways with Start Calligraphy- Right Way to Write. Calligraphy is much more than stylish font and is more about visual art. Each writing style execution demands dedication and practice. Start Calligraphy- Right Way to Right offer you step-by-step method to master different writing and lettering styles. Even children as young as age 10 can learn calligraphy effortlessly. The book has 224 pages, which is filled with countless writing styles and techniques. Apart from traditional writing styles, the book also offers methodical training of non-classical handwriting and modern calligraphy. Learning calligraphy can be fun if you do it the right way. Starting right is the key to progress and master the skill.", price: "119.0", image_url: nil, image: File.open("#{Rails.root}/public/uploads/Start_Calligraphy_-_The_Right_Way_to_Write.jpg"), staff_id: 1, author_id: 4, manufacturer_id: 3},
  {name: "The Adventures of Sherlock Holmes (Wisehouse Classics Edition)", description: "THE ADVENTURES OF SHERLOCK HOLMES is a collection of twelve short stories by Arthur Conan Doyle, featuring his fictional detective Sherlock Holmes. It was first published on 14 October 1892, though the individual stories had been serialised in The Strand Magazine between June 1891 and July 1892. The stories are not in chronological order, and the only characters common to all twelve are Holmes and Dr. Watson. As with all but four of the Sherlock Holmes stories, those contained within The Adventures of Sherlock Holmes are told by a first-person narrative from the point of view of Dr. Watson.", price: "524.0", image_url: nil, image: File.open("#{Rails.root}/public/uploads/The_Adventures_of_Sherlock_Holmes__Wisehouse_Classics_Edition_.jpg"), staff_id: 1, author_id: 6, manufacturer_id: 2},
  {name: "Call of the Herald: Young Adult Epic Fantasy (The Dawning of Power trilogy Book 1) ", description: "Call of the Herald is book one of The Dawning of Power trilogy. Echoes of the ancients' power are distant memories, tattered and faded by the passage of eons, but that is about to change. A new dawn has arrived. Latent abilities, harbored in mankind's deepest fibers, wait to be unleashed. Ancient evils awaken, and old fears ignite the fires of war.", price: "1.0", image_url: nil, image: File.open("#{Rails.root}/public/uploads/Call_of_the_Herald_-_Young_Adult_Epic_Fantasy__The_Dawning_of_Power_trilogy_Book_1_.jpg"), staff_id: 1, author_id: 6, manufacturer_id: 2},
  {name: "Blood Magic: A Short Horror Story", description: "When they found the first body, no one batted an eye. \r\n\r\nThat was par for the course in Skid Row. But something with these deaths was off. They were made to look like ritualistic suicides, like something supernatural. But I knew better. Besides, I don't believe in magic. \r\n\r\nMy name is Rick Danvers and I'm an undercover detective with Robbery Homicide. I've been embedded in this slum for a week now, and before the night is over, I'm gonna get to the bottom of the Skid Row Suicides.", price: "299.0", image_url: nil, image: File.open("#{Rails.root}/public/uploads/Blood_Magic_-_A_Short_Horror_Story.jpg"), staff_id: 1, author_id: 5, manufacturer_id: 2}
])
Book::HABTM_Category.create!([
  {book_id: 3, category_id: 1},
  {book_id: 4, category_id: 1},
  {book_id: 4, category_id: 2},
  {book_id: 5, category_id: 1},
  {book_id: 6, category_id: 1},
  {book_id: 7, category_id: 1},
  {book_id: 7, category_id: 5},
  {book_id: 8, category_id: 4},
  {book_id: 9, category_id: 4},
  {book_id: 10, category_id: 4},
  {book_id: 11, category_id: 4},
  {book_id: 13, category_id: 3},
  {book_id: 14, category_id: 3},
  {book_id: 15, category_id: 3},
  {book_id: 16, category_id: 3},
  {book_id: 16, category_id: 5},
  {book_id: 17, category_id: 3},
  {book_id: 17, category_id: 5},
  {book_id: 13, category_id: 5},
  {book_id: 14, category_id: 5},
  {book_id: 15, category_id: 5},
  {book_id: 18, category_id: 2},
  {book_id: 19, category_id: 2},
  {book_id: 20, category_id: 2},
  {book_id: 21, category_id: 2},
  {book_id: 22, category_id: 5},
  {book_id: 23, category_id: 3},
  {book_id: 23, category_id: 5},
  {book_id: 24, category_id: 2},
  {book_id: 24, category_id: 3},
  {book_id: 24, category_id: 5},
  {book_id: 1, category_id: 2},
  {book_id: 1, category_id: 5},
  {book_id: 2, category_id: 2},
  {book_id: 2, category_id: 5},
  {book_id: 12, category_id: 3},
  {book_id: 12, category_id: 5}
])
Cart.create!([
  {},
  {},
  {}
])
Category.create!([
  {name: "Action & Adventure", description: "Action film is a film genre in which the characters are thrust into a series of challenges that involve violence, close combat, physical feats and frantic pursuits. Action films tend to feature a resourceful hero struggling against incredible odds, which include life-threatening situations, a villain, or a pursuit which generally concludes in victory for the hero."},
  {name: "Arts, Film & Photography", description: "Photography is the science, art and practice of creating durable images by recording light or other electromagnetic radiation, either electronically by means of an image sensor, or chemically by means of a light-sensitive material such as photographic film.[1]"},
  {name: "Comics & Mangas", description: "Manga (漫画 Manga?) are comics created in Japan or by creators in the Japanese language, conforming to a style developed in Japan in the late 19th century.[1] They have a long and complex pre-history in earlier Japanese art.[2]"},
  {name: "Computing, Internet & Digital Media", description: "Digital media are any media that are encoded in a machine-readable format.[1] Digital media can be created, viewed, distributed, modified and preserved on digital electronics devices. Computer programs and software; digital imagery, digital video; video games; web pages and websites, including social media; data and databases; digital audio, such as mp3s; and e-books are examples of digital media. "},
  {name: "Fantasy, Horror & Science Fiction", description: "Science fiction is a genre of speculative fiction dealing with imaginative concepts such as futuristic science and technology, space travel, time travel, faster than light travel, parallel universes and extraterrestrial life. Science fiction often explores the potential consequences of scientific and other innovations, and has been called a \"literature of ideas.\"[1]"}
])
Manufacturer.create!([
  {name: "Time magazine", address: "New York City, New York", phone: "234551667277", fax: "167552746662"},
  {name: "The New York Times", address: "The New York Times Building 620 Eighth Avenue Thành phố New York , 10018", phone: "213213213213", fax: "231231232132"},
  {name: "Bloomsbury Publishing", address: "London", phone: "324123412341", fax: "341234123421"},
  {name: "Scholastic Corporation", address: "557 Broadway New York City New York", phone: "132213213231", fax: "213213213213"},
  {name: "Time Warner", address: "New York City, New York, U.S.", phone: "432412343124", fax: "134123432143"},
  {name: "Shueisha", address: "Chiyoda, Tokyo, Japan", phone: "12321321", fax: "2313213"}
])
Staff.create!([
  {name: "admin", birthday: "2016-06-22", gender: "Nam", phone: "123456789", address: "admin 123", email: "admin@example.com", user: "admin", password_digest: "$2a$10$JTiYpwfo/o34fZJ2/v66FeTlx9C78oQhniFrjZ72h1pA6Tk/b/AZi", admin: true},
  {name: "le van tan", birthday: "2016-06-22", gender: "Nam", phone: "123231232132", address: "asdasd123123", email: "levantan@example.com", user: "levantan", password_digest: "$2a$10$svBa3oS3x7zUAuv2Ljn4nuYtnxT7pdz8ILWrq9iFqJTxY36Ozinae", admin: false},
  {name: "leminhsang", birthday: "2016-06-21", gender: "Nam", phone: "123213213213", address: "asda123213", email: "leminhsang@gmail.com", user: "leminhsang", password_digest: "$2a$10$yIBF1UBGbukumqyuF48CqOMSbxwoUk0Gpnr1yaPJk5YXEB78q3gT2", admin: false}
])
